# Generated by Django 4.1.3 on 2022-12-12 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cli_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cli_nom', models.CharField(max_length=255)),
                ('cli_tipo', models.CharField(max_length=255)),
                ('cli_dir', models.CharField(max_length=255)),
                ('cli_aceptacion', models.SmallIntegerField()),
                ('fk_cli_ciu', models.ForeignKey(db_column='fk_cli_ciu', on_delete=django.db.models.deletion.CASCADE, to='productores.ciudad')),
            ],
            options={
                'db_table': 'cliente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('cont_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cont_emision', models.DateField()),
                ('cont_vencimiento', models.DateField()),
                ('cont_descuento', models.SmallIntegerField(blank=True, null=True)),
                ('cont_total', models.TextField()),
                ('cont_transporte', models.CharField(max_length=255)),
                ('cont_status', models.CharField(max_length=255)),
                ('fk_cont_cli', models.ForeignKey(db_column='fk_cont_cli', on_delete=django.db.models.deletion.CASCADE, to='transaccion.cliente')),
                ('fk_cont_p', models.ForeignKey(db_column='fk_cont_p', on_delete=django.db.models.deletion.CASCADE, to='productores.productor')),
            ],
            options={
                'db_table': 'contrato',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DetalleV',
            fields=[
                ('dv_cantidad', models.IntegerField()),
                ('dv_decuento', models.SmallIntegerField(blank=True, null=True)),
                ('fk_dv_cont1', models.OneToOneField(db_column='fk_dv_cont1', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='transaccion.contrato')),
                ('fk_dv_cont2', models.IntegerField()),
                ('fk_dv_cont3', models.IntegerField()),
                ('fk_dv_cult', models.ForeignKey(db_column='fk_dv_cult', on_delete=django.db.models.deletion.CASCADE, to='productores.cultivo')),
            ],
            options={
                'db_table': 'detalle_v',
                'managed': True,
                'unique_together': {('fk_dv_cont1', 'fk_dv_cont2', 'fk_dv_cont3', 'fk_dv_cult')},
            },
        ),
        migrations.CreateModel(
            name='FormaPago',
            fields=[
                ('fp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('fp_tipo', models.CharField(max_length=255)),
                ('fp_cant', models.TextField(blank=True, null=True)),
                ('fp_porc', models.SmallIntegerField(blank=True, null=True)),
                ('fp_cuota', models.SmallIntegerField(blank=True, null=True)),
                ('fp_emision', models.DateField(blank=True, null=True)),
                ('fp_envio', models.DateField(blank=True, null=True)),
                ('fk_fp_p', models.ForeignKey(db_column='fk_fp_p', on_delete=django.db.models.deletion.CASCADE, to='productores.productor')),
            ],
            options={
                'db_table': 'forma_pago',
                'managed': True,
                'unique_together': {('fp_id', 'fk_fp_p')},
            },
        ),
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('conv_id', models.IntegerField(primary_key=True, serialize=False)),
                ('conv_ben', models.CharField(max_length=255)),
                ('conv_fechaini', models.DateField()),
                ('conv_fechafin', models.DateField(blank=True, null=True)),
                ('fk_conv_pp2', models.IntegerField(blank=True, null=True)),
                ('fk_conv_asoc', models.ForeignKey(blank=True, db_column='fk_conv_asoc', null=True, on_delete=django.db.models.deletion.CASCADE, to='productores.asociacion')),
                ('fk_conv_pp1', models.ForeignKey(blank=True, db_column='fk_conv_pp1', null=True, on_delete=django.db.models.deletion.CASCADE, to='productores.pprov')),
            ],
            options={
                'db_table': 'convenio',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='contrato',
            name='fk_forma_pago',
            field=models.ForeignKey(db_column='fk_forma_pago', on_delete=django.db.models.deletion.CASCADE, to='transaccion.formapago'),
        ),
        migrations.CreateModel(
            name='Renovacion',
            fields=[
                ('ren_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ren_renovar', models.DateField()),
                ('ren_total', models.TextField()),
                ('fk_ren_cont2', models.IntegerField()),
                ('fk_ren_cont3', models.IntegerField()),
                ('fk_ren_cont1', models.ForeignKey(db_column='fk_ren_cont1', on_delete=django.db.models.deletion.CASCADE, to='transaccion.contrato')),
            ],
            options={
                'db_table': 'renovacion',
                'managed': True,
                'unique_together': {('ren_id', 'fk_ren_cont1', 'fk_ren_cont2', 'fk_ren_cont3')},
            },
        ),
        migrations.CreateModel(
            name='PrecioPromedio',
            fields=[
                ('pro_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pro_fechaini', models.DateField()),
                ('pro_fechafin', models.DateField(blank=True, null=True)),
                ('pro_precio', models.TextField()),
                ('pro_calibre', models.CharField(max_length=255)),
                ('fk_pro_pais', models.ForeignKey(db_column='fk_pro_pais', on_delete=django.db.models.deletion.CASCADE, to='productores.pais')),
                ('fk_pro_v', models.ForeignKey(db_column='fk_pro_v', on_delete=django.db.models.deletion.CASCADE, to='productores.variedad')),
            ],
            options={
                'db_table': 'precio_promedio',
                'managed': True,
                'unique_together': {('pro_id', 'fk_pro_v', 'fk_pro_pais')},
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('pag_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pag_fecha', models.DateField()),
                ('pag_monto', models.TextField()),
                ('fk_pag_cont2', models.IntegerField()),
                ('fk_pag_cont3', models.IntegerField()),
                ('fk_pag_cont1', models.ForeignKey(db_column='fk_pag_cont1', on_delete=django.db.models.deletion.CASCADE, to='transaccion.contrato')),
            ],
            options={
                'db_table': 'pago',
                'managed': True,
                'unique_together': {('pag_id', 'fk_pag_cont1', 'fk_pag_cont2', 'fk_pag_cont3')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='contrato',
            unique_together={('cont_id', 'fk_cont_cli', 'fk_cont_p')},
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('env_id', models.IntegerField(primary_key=True, serialize=False)),
                ('env_cantidad', models.IntegerField()),
                ('fk_env_dv2', models.IntegerField()),
                ('fk_env_dv3', models.IntegerField()),
                ('fk_env_dv4', models.IntegerField()),
                ('fk_env_v', models.ForeignKey(db_column='fk_env_v', on_delete=django.db.models.deletion.CASCADE, to='productores.variedad')),
                ('fk_env_dv1', models.ForeignKey(db_column='fk_env_dv1', on_delete=django.db.models.deletion.CASCADE, to='transaccion.detallev')),
            ],
            options={
                'db_table': 'envio',
                'managed': True,
                'unique_together': {('env_id', 'fk_env_v', 'fk_env_dv1', 'fk_env_dv2', 'fk_env_dv3', 'fk_env_dv4')},
            },
        ),
    ]
