# Generated by Django 4.1.3 on 2022-12-12 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transaccion', '0001_initial'),
        ('productores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('var_id', models.IntegerField(primary_key=True, serialize=False)),
                ('var_nom', models.CharField(max_length=255)),
                ('var_desc', models.CharField(max_length=255)),
                ('var_tipo', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'variable',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ResultadoEvalAnual',
            fields=[
                ('rea_year', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('rea_valor', models.SmallIntegerField()),
                ('rea_porc', models.SmallIntegerField()),
                ('rea_fecha', models.DateField()),
                ('rea_decision', models.CharField(max_length=255)),
                ('fk_rea_cli', models.ForeignKey(db_column='fk_rea_cli', on_delete=django.db.models.deletion.CASCADE, to='transaccion.cliente')),
                ('fk_rea_p', models.ForeignKey(db_column='fk_rea_p', on_delete=django.db.models.deletion.CASCADE, to='productores.productor')),
            ],
            options={
                'db_table': 'resultado_eval_anual',
                'managed': True,
                'unique_together': {('rea_year', 'fk_rea_cli', 'fk_rea_p')},
            },
        ),
        migrations.CreateModel(
            name='Formula',
            fields=[
                ('for_id', models.IntegerField(primary_key=True, serialize=False)),
                ('for_tipo', models.CharField(max_length=255)),
                ('for_import', models.TextField()),
                ('fk_for_cli', models.ForeignKey(db_column='fk_for_cli', on_delete=django.db.models.deletion.CASCADE, to='transaccion.cliente')),
                ('fk_for_var', models.ForeignKey(db_column='fk_for_var', on_delete=django.db.models.deletion.CASCADE, to='evaluacion.variable')),
            ],
            options={
                'db_table': 'formula',
                'managed': True,
                'unique_together': {('for_id', 'fk_for_cli', 'fk_for_var')},
            },
        ),
    ]
