# Generated by Django 4.1.3 on 2022-12-12 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asociacion',
            fields=[
                ('asoc_id', models.IntegerField(primary_key=True, serialize=False)),
                ('asoc_nom', models.CharField(max_length=255)),
                ('asoc_dir', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'asociacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('ciu_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ciu_nom', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ciudad',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Padrino',
            fields=[
                ('pad_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pad_nom', models.CharField(max_length=255)),
                ('pad_seg_nom', models.CharField(blank=True, max_length=255, null=True)),
                ('pad_ape', models.CharField(max_length=255)),
                ('pad_seg_ape', models.CharField(blank=True, max_length=255, null=True)),
                ('fk_pad_ciu', models.ForeignKey(db_column='fk_pad_ciu', on_delete=django.db.models.deletion.CASCADE, to='productores.ciudad')),
            ],
            options={
                'db_table': 'padrino',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('pais_id', models.IntegerField(primary_key=True, serialize=False)),
                ('pais_nom', models.CharField(max_length=255)),
                ('pais_continente', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'pais',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Productor',
            fields=[
                ('p_id', models.IntegerField(primary_key=True, serialize=False)),
                ('p_nom', models.CharField(max_length=255)),
                ('p_dir', models.CharField(max_length=255)),
                ('p_envase', models.CharField(max_length=255)),
                ('fk_p', models.ForeignKey(blank=True, db_column='fk_p', null=True, on_delete=django.db.models.deletion.CASCADE, to='productores.productor')),
                ('fk_p_asoc', models.ForeignKey(blank=True, db_column='fk_p_asoc', null=True, on_delete=django.db.models.deletion.CASCADE, to='productores.asociacion')),
                ('fk_p_ciu', models.ForeignKey(db_column='fk_p_ciu', on_delete=django.db.models.deletion.CASCADE, to='productores.ciudad')),
            ],
            options={
                'db_table': 'productor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Variedad',
            fields=[
                ('v_id', models.IntegerField(primary_key=True, serialize=False)),
                ('v_nom', models.CharField(max_length=255)),
                ('v_maduracion', models.CharField(blank=True, max_length=255, null=True)),
                ('v_paisorigen', models.CharField(max_length=255)),
                ('v_desc', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'variedad',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('reg_id', models.IntegerField(primary_key=True, serialize=False)),
                ('reg_nom', models.CharField(max_length=255)),
                ('fk_reg_pais', models.ForeignKey(db_column='fk_reg_pais', on_delete=django.db.models.deletion.CASCADE, to='productores.pais')),
            ],
            options={
                'db_table': 'region',
                'managed': True,
                'unique_together': {('reg_id', 'fk_reg_pais')},
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('prov_id', models.IntegerField(primary_key=True, serialize=False)),
                ('prov_nom', models.CharField(max_length=255)),
                ('prov_negocio', models.CharField(max_length=255)),
                ('prov_dir', models.CharField(max_length=255)),
                ('fk_prov_ciu', models.ForeignKey(db_column='fk_prov_ciu', on_delete=django.db.models.deletion.CASCADE, to='productores.ciudad')),
            ],
            options={
                'db_table': 'proveedor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cultivo',
            fields=[
                ('cult_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cult_calibre', models.CharField(max_length=255)),
                ('cult_prodanual', models.IntegerField()),
                ('cult_periodoini', models.DateField()),
                ('cult_periodofin', models.DateField()),
                ('cult_destexport', models.IntegerField()),
                ('fk_cult_p', models.ForeignKey(db_column='fk_cult_p', on_delete=django.db.models.deletion.CASCADE, to='productores.productor')),
                ('fk_cult_v', models.ForeignKey(db_column='fk_cult_v', on_delete=django.db.models.deletion.CASCADE, to='productores.variedad')),
            ],
            options={
                'db_table': 'cultivo',
                'managed': True,
                'unique_together': {('cult_id', 'fk_cult_v', 'fk_cult_p')},
            },
        ),
        migrations.AddField(
            model_name='ciudad',
            name='fk_ciu_pais',
            field=models.ForeignKey(db_column='fk_ciu_pais', on_delete=django.db.models.deletion.CASCADE, to='productores.pais'),
        ),
        migrations.AddField(
            model_name='asociacion',
            name='fk_asoc_reg',
            field=models.ForeignKey(db_column='fk_asoc_reg', on_delete=django.db.models.deletion.CASCADE, to='productores.region'),
        ),
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('prod_id', models.IntegerField(primary_key=True, serialize=False)),
                ('prod_year', models.DateField()),
                ('prod_logradakg', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('fk_prod_cult', models.ForeignKey(db_column='fk_prod_cult', on_delete=django.db.models.deletion.CASCADE, to='productores.cultivo')),
                ('fk_prod_v', models.ForeignKey(db_column='fk_prod_v', on_delete=django.db.models.deletion.CASCADE, to='productores.variedad')),
            ],
            options={
                'db_table': 'produccion',
                'managed': True,
                'unique_together': {('prod_id', 'fk_prod_v', 'fk_prod_cult')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='ciudad',
            unique_together={('ciu_id', 'fk_ciu_pais')},
        ),
        migrations.CreateModel(
            name='PProv',
            fields=[
                ('fk_pp_p', models.OneToOneField(db_column='fk_pp_p', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='productores.productor')),
                ('fk_pp_prov', models.ForeignKey(db_column='fk_pp_prov', on_delete=django.db.models.deletion.CASCADE, to='productores.proveedor')),
            ],
            options={
                'db_table': 'p_prov',
                'managed': True,
                'unique_together': {('fk_pp_p', 'fk_pp_prov')},
            },
        ),
        migrations.CreateModel(
            name='Apadrinamiento',
            fields=[
                ('ap_fechaini', models.DateField()),
                ('ap_fechafin', models.DateField(blank=True, null=True)),
                ('ap_aporte', models.TextField(blank=True, null=True)),
                ('fk_ap_pad', models.OneToOneField(db_column='fk_ap_pad', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='productores.padrino')),
                ('fk_ap_p', models.ForeignKey(db_column='fk_ap_p', on_delete=django.db.models.deletion.CASCADE, to='productores.productor')),
                ('fk_ap_v', models.ForeignKey(db_column='fk_ap_v', on_delete=django.db.models.deletion.CASCADE, to='productores.variedad')),
            ],
            options={
                'db_table': 'apadrinamiento',
                'managed': True,
                'unique_together': {('fk_ap_pad', 'fk_ap_p', 'fk_ap_v')},
            },
        ),
    ]
