# Generated by Django 4.1.3 on 2022-12-12 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transaccion', '0001_initial'),
        ('productores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('ing_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ing_nom', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'ingrediente',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('rec_id', models.IntegerField(primary_key=True, serialize=False)),
                ('rec_nom', models.CharField(max_length=255)),
                ('rec_tipo', models.CharField(max_length=255)),
                ('rec_tiempo', models.TimeField()),
                ('rec_raciones', models.SmallIntegerField()),
                ('rec_autor', models.CharField(blank=True, max_length=255, null=True)),
                ('fk_rec_cli', models.ForeignKey(blank=True, db_column='fk_rec_cli', null=True, on_delete=django.db.models.deletion.CASCADE, to='transaccion.cliente')),
                ('fk_rec_p', models.ForeignKey(blank=True, db_column='fk_rec_p', null=True, on_delete=django.db.models.deletion.CASCADE, to='productores.productor')),
            ],
            options={
                'db_table': 'receta',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Elaboracion',
            fields=[
                ('elab_paso', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('elab_desc', models.CharField(max_length=255)),
                ('fk_elab_rec', models.ForeignKey(db_column='fk_elab_rec', on_delete=django.db.models.deletion.CASCADE, to='recetas.receta')),
            ],
            options={
                'db_table': 'elaboracion',
                'managed': True,
                'unique_together': {('elab_paso', 'fk_elab_rec')},
            },
        ),
        migrations.CreateModel(
            name='VReceta',
            fields=[
                ('cantgr', models.IntegerField()),
                ('fk_vr_rec', models.OneToOneField(db_column='fk_vr_rec', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='recetas.receta')),
                ('fk_vr_v', models.ForeignKey(db_column='fk_vr_v', on_delete=django.db.models.deletion.CASCADE, to='productores.variedad')),
            ],
            options={
                'db_table': 'v_receta',
                'managed': True,
                'unique_together': {('fk_vr_rec', 'fk_vr_v')},
            },
        ),
        migrations.CreateModel(
            name='IngredienteReceta',
            fields=[
                ('ir_cantidad', models.IntegerField(blank=True, null=True)),
                ('ir_unidad', models.CharField(blank=True, max_length=255, null=True)),
                ('fk_ir_rec', models.OneToOneField(db_column='fk_ir_rec', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='recetas.receta')),
                ('fk_ir_ing', models.ForeignKey(db_column='fk_ir_ing', on_delete=django.db.models.deletion.CASCADE, to='recetas.ingrediente')),
            ],
            options={
                'db_table': 'ingrediente_receta',
                'managed': True,
                'unique_together': {('fk_ir_rec', 'fk_ir_ing')},
            },
        ),
    ]
